-- +goose Up
-- +goose StatementBegin
CREATE extension if NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS task (
    id uuid DEFAULT uuid_generate_v4 (), /* Autogenerated Unique ID -- UUID */
    task_name VARCHAR(100) NOT NULL, /* Name of the task */
    task_status VARCHAR(100) NOT NULL, /* Name of the dimension label */
    created_at timestamp(0) DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp(0) DEFAULT CURRENT_TIMESTAMP
) ;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP table task;
-- +goose StatementEnd
